name: Release PKGBUILD to the GitHub Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-pkgbuild:
    name: Release PKGBUILD
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Make PKGBUILD
        if: startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/pkgbuild
        env:
          DESCRIPTION: GO GitHub project manager
          LICENSE: MIT
          EMAIL: me@kyoh86.dev
      - name: Check PKGBUILD
        if: startsWith(github.ref, 'refs/tags/')
        uses: edlanglois/pkgbuild-action@v1
      - name: Upload PKGBUILD for a release asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*_PKGBUILD.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload PKGBUILD for an artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "*_PKGBUILD.tar.gz"
